trigger:
  branches:
    include:
    - master
    - login

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    git submodule init
    git submodule update
  displayName: 'Update submodules'

- script: |
    npm install
    npm run build-prod
  displayName: 'npm install, npm run build-prod'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.Repository.Name)'
    publishLocation: 'Container'
